package org.schabi.newpipe.aether

/**
 * Native binding to the Aether bridge library (`libaether_bridge.so`, built
 * from `aether-bridge/` by the Gradle cargo-ndk task).
 *
 * Every method returns a JSON string whose shape mirrors Aether's FFI
 * replies: `{"ok":true,...}` or `{"ok":false,"error":"..."}`. Strings and
 * heap handles (jobs, identities) are managed inside the native code; Kotlin
 * only passes JSON strings and `Long` handle ids.
 */
interface AetherBridge {
    // --- informational -----------------------------------------------------
    fun version(): String

    // --- identity ----------------------------------------------------------

    /** payload: {"path": string, "transport": "masque"|"wg", ...} -> job reply */
    fun identityOpen(payload: String): String
    fun identitySummary(identity: Long): String
    fun identityFree(identity: Long): String

    // --- operations (all return a job id in the reply) ---------------------

    /** payload: {"transport":..., "mode":..., "ip":..., ...} -> job reply */
    fun scanStart(identity: Long, payload: String): String

    /** payload: {"peer":"ip:port","transport":...,"socks":...,"http":?,...} -> job */
    fun verifyStart(identity: Long, payload: String): String

    /** payload: {"peer":"ip:port","transport":...,"socks":...,"http":?,...} -> job */
    fun tunnelStart(identity: Long, payload: String): String

    /** args: JSON array of strings -> job reply */
    fun coreStart(args: String): String

    // --- job control -------------------------------------------------------
    fun jobPoll(job: Long): String
    fun jobCancel(job: Long): String
    fun jobFree(job: Long): String
}

/**
 * Native implementation of [AetherBridge] backed by `libaether_bridge.so`.
 * The JNI symbols are generated by the `aether-bridge` Rust crate and bind
 * directly to Aether's C FFI.
 */
object NativeAetherBridge : AetherBridge {
    init {
        System.loadLibrary("aether_bridge")
    }

    external override fun version(): String
    external override fun identityOpen(payload: String): String
    external override fun identitySummary(identity: Long): String
    external override fun identityFree(identity: Long): String
    external override fun scanStart(identity: Long, payload: String): String
    external override fun verifyStart(identity: Long, payload: String): String
    external override fun tunnelStart(identity: Long, payload: String): String
    external override fun coreStart(args: String): String
    external override fun jobPoll(job: Long): String
    external override fun jobCancel(job: Long): String
    external override fun jobFree(job: Long): String

    /**
     * Load the native bridge and return the Aether engine version. Throws
     * [UnsatisfiedLinkError]/[IllegalStateException] if the library cannot
     * be used; callers map that to a user-visible error.
     */
    fun verifyLoaded(): String = version()
}
