package org.schabi.newpipe.aether

/**
 * Native binding to the Aether bridge library (`libaether_bridge.so`, built
 * from `aether-bridge/` by the Gradle cargo-ndk task).
 *
 * Every method returns a JSON string whose shape mirrors Aether's FFI
 * replies: `{"ok":true,...}` or `{"ok":false,"error":"..."}`. Strings and
 * heap handles (jobs, identities) are managed inside the native code; Kotlin
 * only passes JSON strings and `Long` handle ids.
 */
interface AetherBridge {
    // --- informational -----------------------------------------------------
    fun version(): String

    // --- identity ----------------------------------------------------------

    /** payload: {"path": string, "transport": "masque"|"wg", ...} -> job reply */
    fun identityOpen(payload: String): String
    fun identitySummary(identity: Long): String
    fun identityFree(identity: Long): String

    // --- operations (all return a job id in the reply) ---------------------

    /** payload: {"transport":..., "mode":..., "ip":..., ...} -> job reply */
    fun scanStart(identity: Long, payload: String): String

    /** payload: {"peer":"ip:port","transport":...,"socks":...,"http":?,...} -> job */
    fun verifyStart(identity: Long, payload: String): String

    /** payload: {"peer":"ip:port","transport":...,"socks":...,"http":?,...} -> job */
    fun tunnelStart(identity: Long, payload: String): String

    /** args: JSON array of strings -> job reply */
    fun coreStart(args: String): String

    // --- job control -------------------------------------------------------
    fun jobPoll(job: Long): String
    fun jobCancel(job: Long): String
    fun jobFree(job: Long): String
}

/**
 * Native implementation of [AetherBridge] backed by `libaether_bridge.so`.
 * The JNI symbols are generated by the `aether-bridge` Rust crate and bind
 * directly to Aether's C FFI.
 *
 * The native library is loaded lazily and a load failure is recorded rather
 * than thrown from the class initializer: a throwing `<clinit>` would turn the
 * class into a permanently-unloadable `NoClassDefFoundError` for the whole
 * process (e.g. on devices/ABIs without the .so). Instead, [isLoaded] stays
 * false and every method throws [UnsatisfiedLinkError] at the call site,
 * which the controller maps to a user-visible, degraded state.
 */
object NativeAetherBridge : AetherBridge {
    @Volatile
    private var nativeLoaded = false

    init {
        try {
            System.loadLibrary("aether_bridge")
            nativeLoaded = true
        } catch (e: UnsatisfiedLinkError) {
            nativeLoaded = false
        }
    }

    private fun ensureLoaded(): String {
        if (!nativeLoaded) {
            throw UnsatisfiedLinkError("libaether_bridge.so not available")
        }
        return ""
    }

    override fun version(): String {
        ensureLoaded()
        return nativeVersion()
    }

    override fun identityOpen(payload: String): String {
        ensureLoaded()
        return nativeIdentityOpen(payload)
    }

    override fun identitySummary(identity: Long): String {
        ensureLoaded()
        return nativeIdentitySummary(identity)
    }

    override fun identityFree(identity: Long): String {
        ensureLoaded()
        return nativeIdentityFree(identity)
    }

    override fun scanStart(identity: Long, payload: String): String {
        ensureLoaded()
        return nativeScanStart(identity, payload)
    }

    override fun verifyStart(identity: Long, payload: String): String {
        ensureLoaded()
        return nativeVerifyStart(identity, payload)
    }

    override fun tunnelStart(identity: Long, payload: String): String {
        ensureLoaded()
        return nativeTunnelStart(identity, payload)
    }

    override fun coreStart(args: String): String {
        ensureLoaded()
        return nativeCoreStart(args)
    }

    override fun jobPoll(job: Long): String {
        ensureLoaded()
        return nativeJobPoll(job)
    }

    override fun jobCancel(job: Long): String {
        ensureLoaded()
        return nativeJobCancel(job)
    }

    override fun jobFree(job: Long): String {
        ensureLoaded()
        return nativeJobFree(job)
    }

    /** Whether the native library was successfully loaded. */
    val isLoaded: Boolean get() = nativeLoaded

    /**
     * Load the native bridge and return the Aether engine version. Throws
     * [UnsatisfiedLinkError] if the library cannot be used; callers map that
     * to a user-visible error.
     */
    fun verifyLoaded(): String = version()

    // --- JNI entry points (implemented natively) --------------------------
    // Method names must match the JNI symbols exported by the `aether-bridge`
    // Rust crate (Java_org_schabi_newpipe_aether_NativeAetherBridge_<name>).

    private external fun nativeVersion(): String
    private external fun nativeIdentityOpen(payload: String): String
    private external fun nativeIdentitySummary(identity: Long): String
    private external fun nativeIdentityFree(identity: Long): String
    private external fun nativeScanStart(identity: Long, payload: String): String
    private external fun nativeVerifyStart(identity: Long, payload: String): String
    private external fun nativeTunnelStart(identity: Long, payload: String): String
    private external fun nativeCoreStart(args: String): String
    private external fun nativeJobPoll(job: Long): String
    private external fun nativeJobCancel(job: Long): String
    private external fun nativeJobFree(job: Long): String
}
